### PR TITLE
Refactor abstract client to use synapse-common client / auth-client

### PR DESCRIPTION
**Pull request by paulstatezny**
### Acceptance Criteria
1. Client is DRY -- it doesn't repeat a bunch of the same code from `client` and `auth-client`.
2. Client uses synapse-common `client` and `auth-client` to perform requests, so that refresh tokens are automatically exchanged and update the actual token.
### Tasks
- Do the above refactoring
### Additional Notes
- The goal here is _not_ to repeat any code. Right now there is a ton of repeated code.

### CODE REVIEW

**Comment by paulstatezny** [comment]
:star: *(rejected by SynBot.  Cannot change from S-New to S-Review)* Haven't tested this yet, but figured it would be good to get some developer eyes on it before I keep going this direction.

**Comment by paulstatezny** [comment]
:star: Haven't tested this yet, but figured it would be good to get some developer eyes on it before I keep going this direction.

**Comment by baohx2000** [comment]
:pray: qa, you'll need to do a npm install and maybe bower install after switching lively branches

**Comment by agerbens** [comment]
:o: Oops this shouldn't have been in review, sorry about that. @paulstatezny is going to check to make sure refresh tokens work.

**Pull request closed without merging**
