### PR TITLE
Re-fix token refreshing

### PR DESCRIPTION
**Pull request by synbot**
see https://github.com/synapsestudios/synapse-common/pull/52

## AC
- If making a request with an expired OAuth token, the console will show that the browser:
  - Initially makes request and receives 401
  - Makes request for refreshed token
  - After receiving updated token, remakes original request
- From lively, it will appear as if the request worked like normal.

### CODE REVIEW

**Comment by zpchavez** [comment]
I'm not sure why all those commits are showing up. Maybe because I initially branched off of master, and then merged develop into it.

**Comment by zpchavez** [comment]
Yeah, looks like sometimes people merge into master, and sometimes they merge into develop.

**Comment by paulstatezny** [comment]
`master` needs to be merged into `develop`. That will fix it.

**Comment by zpchavez** [comment]
Why is there both?

**Comment by paulstatezny** [comment]
Probably someone decided we should use the same branching model as projects?

**Comment by paulstatezny** [comment]
:hand:

**Comment by paulstatezny** [comment]
:pray:

**Comment by pcavagna** [comment]
:hand:

**Comment by pcavagna** [comment]
:+1:

**Pull request merged**
