### PR TITLE
Replace Gulp with Webpack

### PR DESCRIPTION
**Pull request by paulstatezny**
### Testing ACs
1. The app runs just like it used to.

### Dev ACs
1. Gulp is gone
1. Webpack builds app.js file
1. Webpack builds app.css file
1. Webpack rebuilds js and css without reloading the page
1. Webpack "emits" media files to the right directory
1. Environment variable replacing works
1. Sourcemaps work
1. JShint and JSXhint run on appropriate files; Webpack shows jshint warnings in the terminal
1. Webpack and Hot Loader start with `npm start`
1. Production builds can be created with `npm run dist`

### Notes
- Biggest difference from the gulp build is that media files will be included with their full path

### CODE REVIEW

**Comment by paulstatezny** [comment]
:star:

**Comment by nearengine** [comment]
Won't this break existing cookbooks?

**Comment by areida** [comment]
Probably, it needs a webserver. The dev-server could be used if we want it just needs one tweak to make page reloads work.

**Comment by nearengine** [comment]
Since all of our cookbooks, I think, are set to pull the latest master of Lively on provision, I don't feel comfortable merging this until we have that resolved

**Comment by paulstatezny** [comment]
@nearengine Yes, thank you for pointing that out. We'll need to update the lively recipes like this:

https://gist.github.com/paulstatezny/4f92699018c4a567dd1f

**Comment by paulstatezny** [comment]
:star:

**Comment by bobeagan** [comment]
@paulstatezny your gist probably needs updating since I believe we no longer should have a dependency on bower.

**Comment by paulstatezny** [comment]
Done

**Comment by nearengine** [comment]
:pray: We need to make issues on projects this will break before merging.

**Comment by agerbens** [comment]
:star: Applied the same changes made in https://github.com/synapsestudios/frontend-template/pull/87

**Comment by paulstatezny** [comment]
:pray:

**Comment by agerbens** [comment]
:pray:

**Comment by pedringt** [comment]
:-1: Receive 404 Not Found when trying to login

**Comment by agerbens** [comment]
Still getting an error after trying to login. Not sure what is happening, but line 3 of config.github.js is attempting to load a markdown file.
```
SyntaxError: Unexpected identifier
   at Module._compile (module.js:439:25)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous> (/Users/synapse/Documents/Github/lively/application/config/config.github.js:3:15)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
```

**Comment by paulstatezny** [comment]
Problem is, Node can't `require` markdown files (which we have Webpack configured to do) and Webpack doesn't have access to Node's `fs` module.

Discussion about this issue here: https://github.com/webpack/webpack/issues/411

**Comment by paulstatezny** [comment]
:star:

**Comment by areida** [comment]
:pray:

**Comment by dmmcinty** [comment]
:-1:

After logging in, then out, attempting to log in a second time will return the user to lively without actually logging them in.

**Comment by paulstatezny** [comment]
Lst

**Comment by paulstatezny** [comment]
:star:

**Comment by nearengine** [comment]
:pray:

**Comment by dmmcinty** [comment]
:+1:

**Pull request merged**
