### PR TITLE
Update synapse-common to version with fixed refresh token handling

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. Expired tokens refresh seamlessly (i.e. lively won't display 401 responses).

### Tasks
- {{list developer tasks here}}

### CODE REVIEW

**Comment by zpchavez** [comment]
Still needs work :o:

**Comment by zpchavez** [comment]
:star:

package.json is currently pointing to a synapse-common branch. Will need to get that merged and update the dependency before merging.

**Comment by spruce-bruce** [comment]
:pray:

**Comment by pcavagna** [comment]
:hand:

**Comment by pcavagna** [comment]
:-1:

Auth credential fields are absent

credential lively

**Comment by zpchavez** [comment]
Those are specified in the config now. You will have to add them in. Under the `api` section of the config file add values for `client_id`, `client_secret`, and `scope`. The last two should be set to empty strings. :pray:

**Comment by aecarr2** [comment]
:hand:

**Comment by aecarr2** [comment]
:+1:

**Comment by paulstatezny** [comment]
Nice!

**Pull request merged**
