### PR TITLE
Add support for simple, non-resumable upload

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. Can specify param with type "file" and it will appear as an upload field.
1. Upload endpoints work.

### Tasks
- {{list developer tasks here}}

### Additional Notes
- {{list additional notes here, remove if not applicable}}

### CODE REVIEW

**Comment by baohx2000** [comment]
:interrobang: 
Looks like after processing the file, lively doesn't allow adding any more params.  Need to be able to provide multiple params including other files.
Lively also doesn't check the required flag to see if a file is provided.

**Comment by zpchavez** [comment]
I was thinking multiple file support would be a separate issue.

I don't think it's Lively's responsibility to enforce required fields. 

:star:

**Comment by baohx2000** [comment]
:pray:

**Comment by pedringt** [comment]
:hand:

**Comment by pedringt** [comment]
:+1:

**Comment by zpchavez** [comment]
Think I spent :five: just trying to figure out how to properly pass the request data as binary.

**Pull request merged**
