### PR TITLE
422 blank field errors when fields aren't blank

### PR DESCRIPTION
**Pull request by synbot**
## Description

Ref #79 

After the addition of the parameter checkboxes, submitting an endpoint will give 422 errors for blank values, even though those fields have values. Submitting a second time will be successful.

### CODE REVIEW

**Comment by baohx2000** [comment]
seems to have fixed it for me :pray:

**Comment by dmmcinty** [comment]
:hand:

**Comment by pedringt** [comment]
Now I'm getting 422 errors every time I submit an endpoint. I set it up to test like #106 but I could have done something wrong.

**Comment by pedringt** [comment]
:-1: Now I'm getting 422 errors every time I submit an endpoint. I set it up to test like #106.

**Comment by zpchavez** [comment]
:star:

**Comment by zpchavez** [comment]
Guess I had just flipped the bug around so that the first request worked and subsequent ones did not.

**Comment by paulstatezny** [comment]
:pray:

**Comment by pedringt** [comment]
:hand:

**Comment by pedringt** [comment]
:+1:

**Pull request merged**
