### PR TITLE
Add 'text' param type

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. A param can be set with type 'text', which creates a multiline text box to enter longer strings

### Tasks
- {{list developer tasks here}}

### Additional Notes
- {{list additional notes here, remove if not applicable}}

### CODE REVIEW

**Comment by paulstatezny** [comment]
:pray:

**Comment by kylecesmat** [comment]
:o:

**Comment by kylecesmat** [comment]
:star:

**Comment by zpchavez** [comment]
:star2:

**Comment by canfie1d** [comment]
:pray:

**Comment by dmmcinty** [comment]
:hand:

**Comment by dmmcinty** [comment]
:+1:

**Pull request merged**
