### PR TITLE
Update lively config files to match Github API

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. The lively config files match the current Github API at https://developer.github.com/v3/
1. Endpoints work as expected.
1. No broken links

### Additional Details
The [Users/Administration (Enterprise) section](https://developer.github.com/v3/users/administration/) and all of the [Enterprise 2.1 section](https://developer.github.com/v3/enterprise/) are being left out for now.

### CODE REVIEW

**Comment by paulstatezny** [comment]
:pray: To test, check the docs and make sure everything lines up. Also, you could test some of the endpoints. But it's probably not reasonable to test all of them.

**Comment by agerbens** [comment]
QA - Also please note that 2 sections were intentionally left out per the Additional Details section.

**Comment by aecarr2** [comment]
:hand:

**Comment by aecarr2** [comment]
:-1:

**Comment by agerbens** [comment]
:star:

**Comment by baohx2000** [comment]
:pray:

**Comment by aecarr2** [comment]
:hand:

**Comment by aecarr2** [comment]
:+1:

**Pull request merged**
